[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "bun run start"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.envs]
NODE_ENV = "production"

[[services]]
internal_port = 3000
protocol = "tcp"

[[services.ports]]
handlers = ["http"]
port = "80"
force_https = true